/*
 * Gabriel Pires Ferreira 201935023
 * Matheus do Nascimento Pereira da Costa 201676003
 * Luiz Henrique de Oliveira Pereira 201635009
 * Paulo Victor de Magalhaes Rozatto 201935027
*/
package br.com.ufjf.estudante.janelas;

/**
 *
 * @author Luiz
 */
public class Janela_Criacao_Personagens extends javax.swing.JFrame {

    /**
     * Creates new form Janela_Criacao_Personagens
     */
    public Janela_Criacao_Personagens() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_selecione_quantidade = new javax.swing.JLabel();
        cbox_quantidade = new javax.swing.JComboBox<>();
        button_confirmar = new javax.swing.JButton();
        cbox_personagens = new javax.swing.JComboBox<>();
        label_selecione_personagem = new javax.swing.JLabel();
        label_nome = new javax.swing.JLabel();
        label_classe = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        button_confirmar_nome = new javax.swing.JButton();
        button_confirmar_classe = new javax.swing.JButton();
        button_iniciar_jogo = new javax.swing.JButton();
        cbox_classe = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_selecione_quantidade.setText("Escolha a quantidade de personagens:");

        cbox_quantidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        button_confirmar.setText("Confirmar");
        button_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_confirmarActionPerformed(evt);
            }
        });

        cbox_personagens.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_selecione_personagem.setText("Selecione o personagem para editar:");

        label_nome.setText("Nome:");

        label_classe.setText("Classe:");

        jTextField1.setText("jTextField1");

        button_confirmar_nome.setText("Confirmar Nome");
        button_confirmar_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_confirmar_nomeActionPerformed(evt);
            }
        });

        button_confirmar_classe.setText("Confirmar Classe");
        button_confirmar_classe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_confirmar_classeActionPerformed(evt);
            }
        });

        button_iniciar_jogo.setText("Iniciar jogo");
        button_iniciar_jogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_iniciar_jogoActionPerformed(evt);
            }
        });

        cbox_classe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(label_selecione_personagem)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbox_personagens, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(label_selecione_quantidade)
                                    .addGap(27, 27, 27)
                                    .addComponent(cbox_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(button_confirmar)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(label_classe)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbox_classe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(label_nome)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(button_confirmar_classe, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(button_confirmar_nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(button_iniciar_jogo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_selecione_quantidade)
                    .addComponent(cbox_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_confirmar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_selecione_personagem)
                    .addComponent(cbox_personagens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nome)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_confirmar_nome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_classe)
                    .addComponent(button_confirmar_classe)
                    .addComponent(cbox_classe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(button_iniciar_jogo)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_confirmarActionPerformed
        // TODO add your handling code here:
        //Confirma quantidade de personagens a serem criados
    }//GEN-LAST:event_button_confirmarActionPerformed

    private void button_confirmar_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_confirmar_nomeActionPerformed
        // TODO add your handling code here:
        //confirma nome do personagem selecionado
    }//GEN-LAST:event_button_confirmar_nomeActionPerformed

    private void button_confirmar_classeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_confirmar_classeActionPerformed
        // TODO add your handling code here:
        //confirma classe do perssonagem selecianado
    }//GEN-LAST:event_button_confirmar_classeActionPerformed

    private void button_iniciar_jogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_iniciar_jogoActionPerformed
        // TODO add your handling code here:
        //Muda para a tela Janela_Transicao
    }//GEN-LAST:event_button_iniciar_jogoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Janela_Criacao_Personagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Janela_Criacao_Personagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Janela_Criacao_Personagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Janela_Criacao_Personagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Janela_Criacao_Personagens().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_confirmar;
    private javax.swing.JButton button_confirmar_classe;
    private javax.swing.JButton button_confirmar_nome;
    private javax.swing.JButton button_iniciar_jogo;
    private javax.swing.JComboBox<String> cbox_classe;
    private javax.swing.JComboBox<String> cbox_personagens;
    private javax.swing.JComboBox<String> cbox_quantidade;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel label_classe;
    private javax.swing.JLabel label_nome;
    private javax.swing.JLabel label_selecione_personagem;
    private javax.swing.JLabel label_selecione_quantidade;
    // End of variables declaration//GEN-END:variables
}
