/*
 * Gabriel Pires Ferreira 201935023
 * Matheus do Nascimento Pereira da Costa 201676003
 * Luiz Henrique de Oliveira Pereira 201635009
 * Paulo Victor de Magalhaes Rozatto 201935027
 */
package br.com.ufjf.estudante.janelas;

import br.com.ufjf.estudante.main.AtackFisico;
import br.com.ufjf.estudante.main.AtackMagico;
import br.com.ufjf.estudante.main.ItemArma;
import br.com.ufjf.estudante.main.ItemArmadura;
import br.com.ufjf.estudante.main.Jogador;
import br.com.ufjf.estudante.main.NpcInimigo;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Luiz
 */
public class Janela_Criacao_Personagens extends javax.swing.JFrame {

    /**
     * Creates new form Janela_Criacao_Personagens
     */
    List<Jogador> grupoJogador = new ArrayList<>();
    List<NpcInimigo> grupoInimigo = new ArrayList<NpcInimigo>();

    private int indiceJogador;
    private int quantidade;

    public Janela_Criacao_Personagens() {
        this.indiceJogador = -1;
        this.quantidade = 0;
        initComponents();
    }

    private void criaJogador() {
        String nome = textField_nome.getText();
        int classe = cbox_classe.getSelectedIndex() + 1;

//        System.out.println("Nome: " + nome + " Classe: " + classe);
        if (classe == 1) {
            int forca = 10;
            int inteligencia = 10;
            int destreza = 10;
            AtackFisico ataqueFisico = new AtackFisico("soco", 10, 10, 1);
            AtackMagico ataqueMagico = new AtackMagico("magia", 10, 10, 10, 1);
            ataqueMagico = new AtackMagico("magia", 5, 5, 5, 0);
            ItemArma arma = new ItemArma(ataqueFisico, 0, "Mãos", 1);
            ItemArmadura armadura = new ItemArmadura("Leve", 4, "tecido");
            Jogador jogador = new Jogador(nome, forca, inteligencia, destreza, classe, arma, armadura);
            grupoJogador.add(jogador);
        }

        if (classe == 2) {
            int forca = 10;
            int inteligencia = 10;
            int destreza = 10;
            AtackFisico ataqueFisico = new AtackFisico("soco", 10, 10, 1);
            AtackMagico ataqueMagico = new AtackMagico("magia", 10, 10, 10, 1);
            ataqueMagico = new AtackMagico("magia", 5, 5, 5, 0);
            ItemArma arma = new ItemArma(ataqueFisico, 0, "Mãos", 1);
            ItemArmadura armadura = new ItemArmadura("Leve", 4, "tecido");
            Jogador jogador = new Jogador(nome, forca, inteligencia, destreza, classe, arma, armadura);
            grupoJogador.add(jogador);
        }

        if (classe == 3) {
            int forca = 10;
            int inteligencia = 10;
            int destreza = 10;
            AtackFisico ataqueFisico = new AtackFisico("soco", 10, 10, 1);
            AtackMagico ataqueMagico = new AtackMagico("magia", 10, 10, 10, 1);
            ataqueMagico = new AtackMagico("magia", 5, 5, 5, 0);
            ItemArma arma = new ItemArma(ataqueFisico, 0, "Mãos", 1);
            ItemArmadura armadura = new ItemArmadura("Leve", 4, "tecido");
            Jogador jogador = new Jogador(nome, forca, inteligencia, destreza, classe, arma, armadura);
            grupoJogador.add(jogador);
        }

    }

    private void editaTextoTela() {
        label_Contexto.setText("Crie o Personagem " + (indiceJogador + 1));
        textField_nome.setText("Personagem " + (indiceJogador + 1));
        if (indiceJogador < 3) {
            cbox_classe.setSelectedIndex(indiceJogador);
        } else {
            cbox_classe.setSelectedIndex(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_selecione_quantidade = new javax.swing.JLabel();
        cbox_quantidade = new javax.swing.JComboBox<>();
        button_confirmarQuantidade = new javax.swing.JButton();
        label_nome = new javax.swing.JLabel();
        label_classe = new javax.swing.JLabel();
        textField_nome = new javax.swing.JTextField();
        button_confirmarCriacao = new javax.swing.JButton();
        button_iniciar_jogo = new javax.swing.JButton();
        cbox_classe = new javax.swing.JComboBox<>();
        label_Contexto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Criação de Personagens");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        label_selecione_quantidade.setText("Escolha a quantidade de personagens:");

        cbox_quantidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        button_confirmarQuantidade.setText("Confirmar");
        button_confirmarQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_confirmarQuantidadeActionPerformed(evt);
            }
        });

        label_nome.setText("Nome:");

        label_classe.setText("Classe:");

        textField_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_nomeActionPerformed(evt);
            }
        });

        button_confirmarCriacao.setText("Confirmar");
        button_confirmarCriacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_confirmarCriacaoActionPerformed(evt);
            }
        });

        button_iniciar_jogo.setText("Iniciar jogo");
        button_iniciar_jogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_iniciar_jogoActionPerformed(evt);
            }
        });

        cbox_classe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guerreiro", "Mago", "Ladino" }));

        label_Contexto.setText("Crie o Personagem .");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label_selecione_quantidade)
                        .addGap(27, 27, 27)
                        .addComponent(cbox_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_confirmarQuantidade)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_Contexto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(label_nome)
                                    .addGap(35, 35, 35)
                                    .addComponent(textField_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(label_classe)
                                    .addGap(29, 29, 29)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(button_confirmarCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbox_classe, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(button_iniciar_jogo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_selecione_quantidade)
                    .addComponent(cbox_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_confirmarQuantidade))
                .addGap(30, 30, 30)
                .addComponent(label_Contexto)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nome)
                    .addComponent(textField_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_classe)
                    .addComponent(cbox_classe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_confirmarCriacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_iniciar_jogo)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //CONFIRMA A QUANTIDADE DE PERSONAGENS A SEREM CRIADOS:
    private void button_confirmarQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_confirmarQuantidadeActionPerformed
        indiceJogador = 0;
        quantidade = cbox_quantidade.getSelectedIndex() + 1;
//        System.out.println("Quantidade: " + quantidade);
        editaTextoTela();
        //Coisas que vao aparecer:
        button_confirmarCriacao.setVisible(true);
        cbox_classe.setVisible(true);
        label_Contexto.setVisible(true);
        label_classe.setVisible(true);
        label_nome.setVisible(true);
        textField_nome.setVisible(true);

        //Coisas que nao vao aparecer        
        cbox_quantidade.setVisible(false);
        button_confirmarQuantidade.setVisible(false);
        label_selecione_quantidade.setVisible(false);
//        button_editar.setVisible(false);
        button_iniciar_jogo.setVisible(false);
    }//GEN-LAST:event_button_confirmarQuantidadeActionPerformed
    //CONFIRMA A CRIACAO DO PERSONAGEM
    private void button_confirmarCriacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_confirmarCriacaoActionPerformed
//        System.out.println("indice: " + indiceJogador + " quantidade: " + quantidade);
        if (indiceJogador < quantidade) {//Se ainda nao foram criado todos os personagens
            criaJogador();
            if (indiceJogador == quantidade - 1) {//Ultimo Personagem foi criado
                //Coisas que vao aparecer:
                button_iniciar_jogo.setVisible(true);
//                button_editar.setVisible(true);

                //Coisas que nao vao aparecer  
                button_confirmarCriacao.setVisible(false);
                cbox_quantidade.setVisible(false);
                button_confirmarQuantidade.setVisible(false);
                label_selecione_quantidade.setVisible(false);
                cbox_classe.setVisible(false);
                label_Contexto.setVisible(false);
                label_classe.setVisible(false);
                label_nome.setVisible(false);
                textField_nome.setVisible(false);
            }
            indiceJogador++;//Proximo Personagem que sera editado
            editaTextoTela();
        }

    }//GEN-LAST:event_button_confirmarCriacaoActionPerformed
    //INICIA JOGO
    private void button_iniciar_jogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_iniciar_jogoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Janela_Batalha(grupoJogador, grupoInimigo).setVisible(true);
    }//GEN-LAST:event_button_iniciar_jogoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Coisas que vao aparecer:
        indiceJogador = 0;//Personagem que sera editado
        cbox_quantidade.setSelectedIndex(3);
        cbox_quantidade.setVisible(true);
        button_confirmarQuantidade.setVisible(true);
        label_selecione_quantidade.setVisible(true);

        //Coisas que nao vao aparecer
        button_confirmarCriacao.setVisible(false);
//        button_editar.setVisible(false);
        button_iniciar_jogo.setVisible(false);
        cbox_classe.setVisible(false);
        label_Contexto.setVisible(false);
        label_classe.setVisible(false);
        label_nome.setVisible(false);
        textField_nome.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void textField_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_nomeActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Janela_Criacao_Personagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Janela_Criacao_Personagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Janela_Criacao_Personagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Janela_Criacao_Personagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Janela_Criacao_Personagens().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_confirmarCriacao;
    private javax.swing.JButton button_confirmarQuantidade;
    private javax.swing.JButton button_iniciar_jogo;
    private javax.swing.JComboBox<String> cbox_classe;
    private javax.swing.JComboBox<String> cbox_quantidade;
    private javax.swing.JLabel label_Contexto;
    private javax.swing.JLabel label_classe;
    private javax.swing.JLabel label_nome;
    private javax.swing.JLabel label_selecione_quantidade;
    private javax.swing.JTextField textField_nome;
    // End of variables declaration//GEN-END:variables
}
